const HttpConstants = {
  // Status Codes
  STATUS_INFORMATIONAL: 100,
  STATUS_SUCCESS: 200,
  STATUS_TEMPORARY_REDIRECT: 307,
  STATUS_BAD_REQUEST: 400,
  STATUS_UNAUTHORIZED: 401,
  STATUS_NOT_FOUND: 404,
  STATUS_INTERNAL: 500
};

export default HttpConstants;
