const SocketConstants = {
  SUBSCRIBE: 'SUBSCRIBE',
  UNSUBSCRIBE: 'UNSUBSCRIBE',
  SUCCESSFUL_CONNECTION: 'SUCCESSFUL_CONNECTION',

  NEW_ORDER: 'NEW_ORDER',
  UPDATE_ORDER_STATUS: 'UPDATE_ORDER_STATUS',
  CANCEL_ORDER: 'CANCEL_ORDER',
  DELETE_UNPAID_CASH_ORDER: 'DELETE_UNPAID_CASH_ORDER',
  NEW_UNPAID_CASH_ORDER: 'NEW_UNPAID_CASH_ORDER',
  UNABLE_TO_FULFILL_ORDER: 'UNABLE_TO_FULFILL_ORDER',

  DELIVERY: 'DELIVERY'
};

export default SocketConstants;
