export enum AccountStatusEnum {
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
  DEACTIVATED = 'DEACTIVATED',
  DELETED = 'DELETED',
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
}
