export enum ComplaintCategoryEnum {
  POOR_ARRIVED_FOOD_CONDITION = 'POOR_ARRIVED_FOOD_CONDITION',
  INCORRECT_FOOD_PREPARATION = 'INCORRECT_FOOD_PREPARATION',
  MISSING_ORDER_ITEM = 'MISSING_ORDER_ITEM',
  WRONG_ORDER = 'WRONG_ORDER',
  MISSING_ORDER = 'MISSING_ORDER',
  SAFETY = 'SAFETY',
  LONG_DELIVERY = 'LONG_DELIVERY',
  MISSING_DELIVERY = 'MISSING_DELIVERY',
  INCORRECT_OUTLET_INFO = 'INCORRECT_OUTLET_INFO',
  POOR_SERVICE = 'POOR_SERVICE',
  INCORRECT_PAYMENT = 'INCORRECT_PAYMENT',
  INCORRECT_CASHBACK = 'INCORRECT_CASHBACK',
  OTHERS = 'OTHERS'
}
