export enum TransactionTypeEnum {
    TOP_UP = 'TOP_UP',
    WITHDRAWAL = 'WITHDRAWAL',
    ORDER = 'ORDER',
    SUBSCRIPTION_PAYMENT = 'SUBSCRIPTION_PAYMENT',
    REFUND = 'REFUND',
    DELIVERY = 'DELIVERY'
}
